### ISSUE TITLE
Support region in Swift backend

### ISSUE THREAD

**Issue by slav0nic** [haiwen/seafobj#7]
Currently backend select first `publicURL` from `endpoints` with type `object-store` without checking region
https://github.com/haiwen/seafobj/blob/master/seafobj/backends/swift.py#L62
for example it does't work for me, example from ovh API response:json
```json
{
            "endpoints": [{
                "adminURL": "https://storage.gra1.cloud.ovh.net",
                "region": "GRA1",
                "internalURL": "http://127.0.0.1:8888/v1/AUTH_xx",
                "id": "xx",
                "publicURL": "https://storage.gra1.cloud.ovh.net/v1/AUTH_xx"
            }, {
                "adminURL": "https://storage.bhs1.cloud.ovh.net:8888/",
                "region": "BHS1",
                "internalURL": "http://127.0.0.1:8888/v1/AUTH_xx",
                "id": "xx",
                "publicURL": "https://storage.bhs1.cloud.ovh.net/v1/AUTH_4e0c05bb47964ede8acf7ede6159bdf4"
            }, {
                "adminURL": "https://storage.sbg1.cloud.ovh.net",
                "region": "SBG1",
                "internalURL": "http://127.0.0.1:8888/v1/AUTH_xx",
                "id": "xx",
                "publicURL": "https://storage.sbg1.cloud.ovh.net/v1/AUTH_xx"
            }],
            "endpoints_links": [],
            "type": "object-store",
            "name": "swift"
        }
```

it will return `storage.gra1.cloud.ovh.net` (`GRA1` region) endpoint, but what if i have storage on another reegion like `SBG1`?

**Comment by slav0nic** [comment]
@killing any response?

**Comment by killing** [comment]
So your suggestion would be to add a configuration option for region?

**Comment by slav0nic** [comment]
yes, like in other clients:  [libcloud](http://libcloud.readthedocs.io/en/latest/storage/drivers/openstack_swift.html#connect-to-openstack-swift-installation) or [python-swiftclient](https://github.com/openstack/python-swiftclient/commit/68d1550f15a6ec6f51973af2e27f3a6943b6305f)

**Comment by killing** [comment]
OK we'll add this option.

**Comment by killing** [comment]
It's added in Pro 6.0.8. Please refer to the manual.

**Comment by slav0nic** [comment]
tnx, works fine
